# Backend https://www.netlifycms.org/docs/configuration-options/#backend
backend:
  name: git-gateway
  branch: master

# Publish mode https://www.netlifycms.org/docs/configuration-options/#publish-mode
publish_mode: editorial_workflow

# Media and Public Folders https://www.netlifycms.org/docs/configuration-options/#media-and-public-folders
media_folder: "app/static/images/uploads" # Media files will be stored in the repo under images/uploads
public_folder: "/images/uploads"

# Collections https://www.netlifycms.org/docs/configuration-options/#collections
collections:
  - label: Seo Landing Page Meta Info
    name: seoLandingPage
    files:
      - label: Meta Info
        name: meta
        format: json
        file: "app/content/metaContent/meta.json"
        fields:
          - { label: "Seo Title", name: "seoTitle", widget: "string" }
          - {
              label: "SEO Description",
              name: "seoDescription",
              widget: "text",
              required: false,
            }
          - {
              label: "SEO Website Name",
              name: "seoWebsiteName",
              widget: "string",
              required: false,
            }
          - {
              label: "SEO Website URL",
              name: "seoWebsiteUrl",
              widget: "string",
              required: false,
            }
          - { label: "Seo Meta Image", name: "seoMetaImage", widget: "image" }
          - {
              label: "SEO Type",
              name: "seoType",
              widget: "string",
              required: false,
            }
          - {
              label: "SEO Language",
              name: "seoLanguage",
              widget: "string",
              required: false,
            }
  - label: Blog
    name: blog
    format: "json"
    create: true
    slug: "{{slug}}"
    sort: "published_date:desc"
    folder: "app/content/blog"
    fields:
      - label: "Preview"
        name: "preview"
        widget: "object"
        collapsed: true
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Excerpt", name: "excerpt", widget: "string" }
          - { label: "Image", name: "image", widget: "image" }
      - label: "Page"
        name: "page"
        widget: "object"
        collapsed: true
        fields:
          - label: "Hero"
            name: "hero"
            widget: "object"
            collapsed: true
            fields: 
              - { label: "Image", name: "image", widget: "image" }
              - { label: "Text", name: "text", widget: "string", required: false }
              # - { 
              #     label: "Color",
              #     name: "color",
              #     widget: "select",
              #     default: "bg-secondary",
              #     options:
              #       - { label: "Black", value: "bg-black" }
              #       - { label: "White", value: "bg-white" }
              #       - { label: "Pink", value: "bg-ld-pink" } 
              #       - { label: "Yellow", value: "bg-ld-yellow" } 
              #       - { label: "Primary", value: "bg-primary" } 
              #       - { label: "Secondary", value: "bg-secondary" }, required: false
              #   }
            
          - label: "Author"
            name: "author"
            widget: "object"
            collapsed: true
            fields: 
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Image", name: "image", widget: "image" }
              - { label: "Minutes Of Read", name: "title", widget: "string", required: false }
              - { label: "Published Date",
                  name: "publishDate",
                  widget: "datetime", 
                  default: "Do MMM YYYY",
                  dateFormat: "Do MMM YYYY", 
                  timeFormat: "HH:mm", 
                  format: "LLL",
                  pickerUtc: true,
                  required: false 
                }

          - label: "Markdown"
            name: "markdown"
            widget: "markdown"
            collapsed: true

          - label: "Button"
            name: "button"
            widget: "object"
            collapsed: true
            fields: 
              - { label: "Text", name: "text", widget: "string" }
              - { label: "Link", name: "link", widget: "string" }
              - label: "Color"
                name: "color" 
                widget: "select"
                required: false
                options:
                  - { label: "Black", value: "bg-black" }
                  - { label: "Pink", value: "bg-ld-pink" } 
                  - { label: "Primary", value: "bg-primary" } 
                  - { label: "Secondary", value: "bg-secondary" } 
                    
          - label: "Seo"
            name: "seo"
            widget: "object"
            collapsed: true
            fields:
              - { label: "Website name", name: "metaWebsiteName", widget: "string", required: false }
              - { label: "Website Url", name: "metaWebsiteUrl", widget: "string", required: false }
              - { label: "Description", name: "metaDescription", widget: "text", required: false }
              - { label: "Image", name: "metaImage", widget: "image" }
              - { label: "Type Article/Website?", name: "metaType", widget: "text", required: false }
              - { label: "Language", name: "metaLanguage", widget: "text", required: false }

          