# Backend https://www.netlifycms.org/docs/configuration-options/#backend
backend:
  name: git-gateway
  branch: master

# Publish mode https://www.netlifycms.org/docs/configuration-options/#publish-mode
publish_mode: editorial_workflow

# Media and Public Folders https://www.netlifycms.org/docs/configuration-options/#media-and-public-folders
media_folder: "app/static/images/uploads" # Media files will be stored in the repo under images/uploads
public_folder: "/images/uploads"

# Collections https://www.netlifycms.org/docs/configuration-options/#collections
collections:
  - label: Seo Landing Page Meta Info
    name: seoLandingPage
    files:
      - label: Meta Info
        name: meta
        format: json
        file: "app/content/metaContent/meta.json"
        required: false
        fields:
          - { label: "Seo Title", name: "seoTitle", widget: "string" }
          - {
              label: "SEO Description",
              name: "seoDescription",
              widget: "text"
            }
          - {
              label: "SEO Website Name",
              name: "seoWebsiteName",
              widget: "string"
            }
          - {
              label: "SEO Website URL",
              name: "seoWebsiteUrl",
              widget: "string"
            }
          - { label: "Seo Meta Image",
              name: "seoMetaImage",
              widget: "image" }
          - {
              label: "SEO Type",
              name: "seoType",
              widget: "string"
            }
          - {
              label: "SEO Language",
              name: "seoLanguage",
              widget: "string"
            }

  - label: Blog
    name: blog
    format: "json"
    create: true
    sort: "published_date:desc"
    folder: "app/content/blog"
    slug: "{{slug}}"
    editor:
      preview: true
    fields:
      - { label: "Preview Image", name: "image", widget: "image" }
      - { label: "Preview Title", name: "title", widget: "string" }
      - { label: "Preview Excerpt", name: "excerpt", widget: "string" }
      - label: "Page"
        name: "page"
        widget: "object"
        collapsed: true
        fields:
          - label: "Hero"
            name: "hero"
            widget: "object"
            collapsed: true
            fields: 
              - { label: "Image", name: "image", widget: "image" }
              - { label: "Text", name: "text", widget: "string", required: false }
              - label: "Color"
                name: "color"
                widget: "select"
                default: "text-secondary"
                required: false
                options:
                  - { label: "Black", value: "text-black" }
                  - { label: "White", value: "text-white" }
                  - { label: "Pink", value: "text-ld-pink" } 
                  - { label: "Yellow", value: "text-ld-yellow" } 
                  - { label: "Primary", value: "text-primary" } 
                  - { label: "Secondary", value: "text-secondary" }

          - label: "Author"
            name: "author"
            widget: "object"
            collapsed: true
            fields: 
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Image", name: "image", widget: "image" }
              - { label: "Minutes Of Read", name: "title", widget: "string"}
              - label: "Published Date"
                name: "publishDate"
                widget: "datetime"
                default: "DD MMM YYYY"
                dateFormat: "DD MMM YYYY"
                timeFormat: "HH:mm"
                format: "LLL"
                pickerUtc: false

          - label: "Markdown"
            name: "markdown"
            widget: "markdown"
            collapsed: true

          - label: "Button"
            name: "button"
            widget: "object"
            collapsed: true
            fields: 
              - { label: "Text", name: "text", widget: "string" }
              - { label: "Link", name: "link", widget: "string" }
              - label: "Color"
                name: "color" 
                widget: "select"
                default: "ld-pink"
                options:
                  - { label: "Black", value: "black" }
                  - { label: "Pink", value: "ld-pink" } 
                  - { label: "Primary", value: "primary" } 
                  - { label: "Secondary", value: "secondary" } 
                    
          - label: "Seo"
            name: "seo"
            widget: "object"
            collapsed: true
            required: false
            fields:
              - { label: "Website name", name: "metaWebsiteName", widget: "string" }
              - { label: "Website Url", name: "metaWebsiteUrl", widget: "string" }
              - { label: "Description", name: "metaDescription", widget: "text" }
              - { label: "Image", name: "metaImage", widget: "image" }
              - { label: "Type Article/Website?", name: "metaType", widget: "text" }
              - { label: "Language", name: "metaLanguage", widget: "text" }

          