# Backend https://www.netlifycms.org/docs/configuration-options/#backend
backend:
  name: git-gateway
  branch: master

# Publish mode https://www.netlifycms.org/docs/configuration-options/#publish-mode
publish_mode: editorial_workflow

# Media and Public Folders https://www.netlifycms.org/docs/configuration-options/#media-and-public-folders
media_folder: "app/static/images/uploads" # Media files will be stored in the repo under images/uploads
public_folder: "/images/uploads"

# Collections https://www.netlifycms.org/docs/configuration-options/#collections
collections:
  - label: Seo Landing Page Meta Info
    name: seoLandingPage
    files:
      - label: Meta Info
        name: meta
        format: json
        file: "app/content/metaContent/meta.json"
        fields:
          - { label: "Seo Title", name: "seoTitle", widget: "string" }
          - {
              label: "SEO Description",
              name: "seoDescription",
              widget: "text",
              required: false,
            }
          - {
              label: "SEO Website Name",
              name: "seoWebsiteName",
              widget: "string",
              required: false,
            }
          - {
              label: "SEO Website URL",
              name: "seoWebsiteUrl",
              widget: "string",
              required: false,
            }
          - { label: "Seo Meta Image", name: "seoMetaImage", widget: "image" }
          - {
              label: "SEO Type",
              name: "seoType",
              widget: "string",
              required: false,
            }
          - {
              label: "SEO Language",
              name: "seoLanguage",
              widget: "string",
              required: false,
            }
  - label: Blog
    name: blog
    format: "json"
    create: true
    slug: "{{slug}}"
    sort: "published_date:desc"
    folder: "app/content/blog"
    fields:
      - label: "Preview"
        name: "preview"
        widget: "object"
        collapsed: true
        fields:
          - { label: "Excerpt", name: "excerpt", widget: "string" }
          - { label: "Image", name: "image", widget: "image" }
          - label: "Title"
            name: "title"
            widget: "string"
      - label: "Page"
        name: "page"
        widget: "object"
        collapsed: true
        fields:
          - label: "Author"
            name: "author"
            widget: "object"
            collapsed: true
            fields: 
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Image", name: "image", widget: "image" }

          